[package]
name = "executor-test-helpers"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos executor test helpers"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
rand = "0.8.3"

aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-genesis-tool = { path = "../../config/management/genesis", features = ["testing"] }
aptos-state-view = { path = "../../storage/state-view" }
aptos-temppath = { path = "../../crates/aptos-temppath" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-types = { path = "../../types", features = ["fuzzing"] }
aptos-vm = { path = "../../aptos-move/aptos-vm" }
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
aptosdb = { path = "../../storage/aptosdb", features = ["fuzzing"] }
executor = { path = "../executor" }
executor-types = { path = "../executor-types" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32"] }
storage-interface = { path = "../../storage/storage-interface" }
storage-service = { path = "../../storage/storage-service" }
vm-genesis = { path = "../../aptos-move/vm-genesis" }
